### ISSUE TITLE
unify the dimension of the flags

### ISSUE THREAD

**Issue by jabbalaci** [ManrajGrover/SingleDivProject#44]
Currently the flag screenshots are all different. There should be a guideline about 1) the size of these images, and 2) the size of the margins around the flags.

**Comment by ManrajGrover** [comment]
@jabbalaci Yes, definitely. Seriously, there is a need to first fix this. Thank you for opening this issue. Would you like to suggest some guidelines?

**Comment by module17** [comment]
@jabbalaci Agreed. Also, perhaps the correct flag proportions should be enforced. I believe most are defined and shown on Wikipedia.

**Comment by ManrajGrover** [comment]
@module17 Apart from proportions, we should give a set canvas beyond which person cannot go.

Or should we just give exact dimensions? Are there any online tools to check this?

**Comment by module17** [comment]
@ManrajGrover Absolutely. Perhaps we can set a maximum width. The proportions will vary, but we can limit the "display width" of the div representation as well as any included assets. Hmm, but then again some flags with such a small maximum width wouldn't be able to show the finer details adequately. 600 pixels?

**Comment by module17** [comment]
Also, @jabbalaci I agree that whitespace guidelines should exist as well. I don't see a reason for any whitespace or margins personally.

**Comment by jabbalaci** [comment]
I think some pixels can be allowed for the margins, but not much more. It could be difficult to crop the flag perfectly, but some pixel rows and columns around the flag are acceptable IMO.

**Comment by module17** [comment]
@jabbalaci If we use SVG and generate PNG from fixed SVG export size we can be consistent. Maybe?

**Comment by ManrajGrover** [comment]
A good and fast solution to this looks to be mentioned [here](http://stackoverflow.com/questions/14675913/how-to-change-image-size-markdown). I'll try it out soon or would love a PR for fixing this. :smile:

**Comment by ManrajGrover** [comment]
This has now been fixed. :smile: Closing this.
