### ISSUE TITLE
Suggestion : Update README

### ISSUE THREAD

**Issue by AnubrataDS** [ManrajGrover/SingleDivProject#73]
An introductory paragraph (even a few lines) in the readme would be awesome !

I stumbled across this project while browsing interesting repositories , and at first was unable to understand what this was all about. After a few minutes I understood it , and i really like the concept .

**Comment by netham91** [comment]
I agree, I sent the links to few friends and they asked the same.

**Comment by ManrajGrover** [comment]
@AnubrataDS @netham91 I have added new sections on `What is this?` and `Why?` to README.md.
Let me know if you would like to add more information to it or suggest some additions. :smile:

**Comment by AnubrataDS** [comment]
The introduction is good and has a sense of playful challenge to it . I like it .

**Comment by netham91** [comment]
It's good and explains the point in a line :)
One suggestion, add a link to contributions.md or maybe add the whole text before license in the end. I got excited on seeing the project and sent a PR without seeing the doc, so maybe it will help guys like me, and will save your time maybe :)

p.s. @AnubrataDS Congrats on your first PR on github 👍

**Comment by AnubrataDS** [comment]
@netham91 Thanks a lot !

**Comment by ManrajGrover** [comment]
@netham91 Sure, will do. :smile: 
@AnubrataDS Thank you for sending a PR. I'll review it soon. :blush:

**Comment by AnubrataDS** [comment]
@ManrajGrover Thanks a lot ! And I really like this project , I'll contribute more stuff to it :+1:

**Comment by ManrajGrover** [comment]
@AnubrataDS Awesome! Waiting for it. :smile:
