### ISSUE TITLE
Play Loader code not working properly

### ISSUE THREAD

**Issue by AnubrataDS** [ManrajGrover/SingleDivProject#76]
I tried running the Play Loader code on windows 8.1 on the browsers Firefox 47.0 and IE 11 and the results were quite weird :-

On Firefox 47.0 :-

![play_loader_firefox](https://cloud.githubusercontent.com/assets/20087176/16365230/a687c666-3c17-11e6-8b4a-00e9e20104a5.gif)

On IE11 :-

![play_loader_ie11](https://cloud.githubusercontent.com/assets/20087176/16365267/b0b4a298-3c18-11e6-889f-836602d5e256.gif)

**Comment by ManrajGrover** [comment]
@AnubrataDS Hey! All these divs were not made to support every browser. They were made just to showcase the possibility. Browser support isn't the aim of the project.
